name: C/C++ CI

on:
  push:
    branches: [ oculus-go-kernel-master ]
  pull_request:
    branches: [ oculus-go-kernel-master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
